### PR TITLE
add support for mouse events

### LINKED ISSUE #51: Listen for mouse events as well?
Would it be possible to listen for mousedown, mousemove, and mouseup as well?

This would be useful when a device has touch capability but the user is using a mouse. (e.g. touch laptops like Surface Pro)

### PR DESCRIPTION
**Pull request by jakepusateri**
Fixes #51

### CODE REVIEW

**Comment by goatslacker** [comment]
This library was meant for touch and not for mouse. I appreciate the PR, perhaps you can fork the project and add it in?

**Comment by jakepusateri** [comment]
What about 'swipeable' means 'only touch events'? For a user with only a mouse, click + drag is a swipe.

If this needs to be an opt-in feature, I can add that option.

**Comment by timpler** [comment]
@goatslacker Whats wrong with making mouse support optional?

**Comment by hartzis** [comment]
I didn't realize devices like the surface pro treat the touch pen as a mouse. I think this is an interesting idea and do think this could be added as an opt-in feature.

@goatslacker how do you feel about adding this as an opt-in feature?

**Comment by goatslacker** [comment]
I'll defer to your judgement @hartzis opt-in is fine.

**Comment by hartzis** [comment]
@jakepusateri do you think you could make another PR with this as an opt in via a prop?

**Pull request closed without merging**
