### PR TITLE
update build process

### PR DESCRIPTION
**Pull request by hartzis**
Introduce modern build:
* add 'src' dir that contains the source of `Swipeable`
* add build process that creates 'lib' dir and publishable `Swipeable`

Part of #18

### CODE REVIEW

**Comment by hartzis** [comment]
If we can get #19 merged squashed and merged in, I'll update this PR.

**Comment by hartzis** [comment]
@goatslacker I'd like to get this merged in. any opinions/concerns? It will cause conflicts with current PR's and users will have to fix/rebase, but none of the current PR's have recent activity.

**Comment by SergeL** [comment]
Hi, what's the status here?

**Comment by chandlerprall** [comment]
@hartzis is at the F8 conference right now, I'll make sure he adds his input here when he gets back. Until then React 15.0.1 emits a warning and doesn't completely falling over.

**Comment by hartzis** [comment]
I think we should get #32 and #33 in before this to avoid conflicts in those PR's.

- [ ] #32 merged in
- [ ] #33 merged in

**Pull request merged**
