### PR TITLE
Extract props

### PR DESCRIPTION
**Pull request by thebuilder**
Fixes warning in 15.2.0

### CODE REVIEW

**Comment by thebuilder** [comment]
I did this change in the Github editor, and haven't tested it. :)

**Comment by hartzis** [comment]
I had a feeling react was going to do something about this. It is a little weird to just spread all the props. I don't know what the best solution is here, but I'd like to get this running on the example to test it at least.

**Comment by thebuilder** [comment]
I agree, but it seems like performing the spread is the simplest way.
The alternative is to clone the object, and delete the internal keys:
```
const divProps = Object.assign({}, props);
delete divProps.layout;
```

**Comment by hartzis** [comment]
The clone and delete are very explicit, I like the use here
https://github.com/JedWatson/react-tappable/blob/master/src/getComponent.js#L45

Long term I still would like to attach swipeables props to the only child
via cloneElement or something similar like that. To avoid this whole issue
hopefully.


On Wednesday, July 6, 2016, Daniel Schmidt <notifications@github.com> wrote:

> I agree, but it seems like performing the spread is the simplest way.
> The alternative is to clone the object, and delete the internal keys:
>
> const divProps = Object.assign({}, props);
> delete divProps.layout;
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/dogfessional/react-swipeable/pull/43#issuecomment-230711340>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFISk7BRBxFQBdasgUc30xFP1Vpxer1cks5qS2h7gaJpZM4JFA7->
> .
>


-- 
Brian Hartz
www.hartzis.me <http://www.hartzis.me/about>
brianhartz@gmail.com

**Comment by emilyaviva** [comment]
I can confirm that this is an issue. I'm doing something like this:
```javascript
class MyComponent extends React.Component {
  render () {
    const {
      onSwipedRight
    } = this.props
    return (
      <Swipeable nodeName='article' onSwipedRight={onSwipedRight}>
        <div className='headline'>blah blah blah</div>
        <p>this is another child element</p>
      </Swipeable>
    )
  }
}
MyComponent.propTypes = {
  onSwipedRight: React.PropTypes.func
}
```
and I'm getting this error message back:
```
Unknown props `nodeName`, `onSwipedRight`, `flickThreshold`, `delta`, `preventDefaultTouchmoveEvent` on <article>
```
I'm not really thrilled with the idea of putting *all* the props in to be explicitly deleted. That doesn't seem very React-like, somehow.

**Comment by hartzis** [comment]
@emilyaviva I agree I don't really 'like' the delete either, just found an example of it in another heavily used touch/swipe library. I do have a long term solution, with `cloneElement`, but it will require an api and major version change.

With the delete method we also avoid name spacing/assigning a bunch of variables that don't actually get used. I think it may be the better short term solution currently.

@thebuilder thank you for this PR and catching the issue, but do you think you could change/update this PR to do the clone/delete method? Let me know if you are unable and/or don't have the time, I could probably get around to it this weekend. Cheers.

**Comment by hartzis** [comment]
solved with #44

**Pull request closed without merging**
